# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('userName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('biography', models.TextField(blank=True, null=True)),
                ('urlAvatar', models.CharField(blank=True, max_length=255, null=True)),
                ('urlBackgroundImage', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('commentTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNameA', models.ForeignKey(db_column='userNameA', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='following_fk_1', to='sounderful.Account')),
                ('userNameB', models.ForeignKey(db_column='userNameB', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='following_fk_2', to='sounderful.Account')),
            ],
            options={
                'db_table': 'following',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('notificationTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('urlTrack', models.CharField(max_length=255)),
                ('urlImage', models.CharField(blank=True, max_length=255, null=True)),
                ('postTime', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('listenNumber', models.IntegerField()),
                ('userName', models.ForeignKey(db_column='userName', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='sounderful.Account')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='postId',
            field=models.ForeignKey(db_column='postId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='sounderful.Post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='userName',
            field=models.ForeignKey(db_column='userName', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='sounderful.Account'),
        ),
        migrations.AddField(
            model_name='like',
            name='postId',
            field=models.ForeignKey(db_column='postId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='sounderful.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='userName',
            field=models.ForeignKey(db_column='userName', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='sounderful.Account'),
        ),
        migrations.AddField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(db_column='postId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='sounderful.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userName',
            field=models.ForeignKey(db_column='userName', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='sounderful.Account'),
        ),
    ]
