# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounderful', '0002_auto_20171123_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
    ]
